### PR TITLE
Add "On Hold" (repeating) actions feature; Also with new TP Settings support.

### PR DESCRIPTION
**Pull request by mpaperno**
* Added support for "On Hold" type Touch Portal actions with a configurable repeat time. 
  All current actions which may make sense to repeat (such as for control surfaces or AP adjustments) should now be available in the "On Hold" TP button configuration page. The generated documentation now shows which actions can be held.
  - Note that "On Hold" actions do _not_ trigger upon first button press, you need to  configure an "On Pressed" action as well, which is a bit more setup but is more flexible.
  in case a single press should do some different action.
* Added Action: Held Action Repeat Rate: Increment/Decrement 50ms or choose one of several presets. The last rate set this way is saved to persistent settings in TP.
* Added State: Current Held Action Repeat Rate
* Added support for Touch Portal plugin Settings (in the TP _Settings -> Plug-ins -> MSFSTouchPortalPlugin_ page).
* Added setting to control automatic connection to SimConnect upon TP (or plugin) startup. When disabled, connection must be made manually via the existing Connect action.

Changes are best reviewed by individual commit.

My main goal was to add repeating actions, so for example I can just hold down my Alt. Adjust bug button until I get to my value, instead of repeated presses. The first 3 commits do that, with a preset repeat delay rate (450ms).

But a set rate is limited (too fast for some things, too slow for others) so I decided to add a Setting for it that the user can control and would persist between runs.  Long story short, this is how the other 2 commits happened, adding overall support for TP Settings.  It's not ideal combining changes like this and I can certainly break things up more (I have everything on separate branches) but with all the other changes/PRs this is getting quickly confusing and interdependent.

On that note, this version is going to have 2 minor conflicts with one or two of the other pending PRs I submitted.  Once those are decided (merged or not), I can rebase this branch on top to ensure no conflicts.  It would be better to get those others out of the way before merging this one, hence I'm marking it as a Draft for now.  But I wanted to get the review/comments flowing.

Thanks!
-Max

### CODE REVIEW

**Comment by mpaperno** [comment]
I have consolidated and published all the changes so far (including my other PRs) on my fork's main branch: https://github.com/mpaperno/MSFSTouchPortalPlugin/tree/mp/main

This includes the updated [DOCUMENTATION](https://github.com/mpaperno/MSFSTouchPortalPlugin/blob/mp/main/DOCUMENTATION.MD) and [CHANGELOG](https://github.com/mpaperno/MSFSTouchPortalPlugin/blob/mp/main/CHANGELOG.md)

I also have made a `Release v0.5.4-mp` of all the changes for others to test with: https://github.com/mpaperno/MSFSTouchPortalPlugin/releases

**Comment by mpaperno** [comment]
I'll submit PRs and request/wait for reviews before merging anything, unless you tell me otherwise  :)

Also, could you drop me a note at mpaperno@worlddesign.com ?  (You'd think GitHub collaborators would have some private way to contact each other, but noooo...)

**Review by tlewis17 — APPROVED** [review]

**Comment by tlewis17** [comment]
There are some conflicts that need to be resolved.

**Comment by mpaperno** [comment]
There are?  GH says no conflicts...?  I haven't checked with actual git.

**Comment by tlewis17** [comment]
Weird, it shows for me:
This branch cannot be rebased due to conflicts

**Comment by mpaperno** [comment]
Something strange is going on... my git just hangs when trying to merge this branch into the current `!release/1.0`, and so does a rebase of this branch onto `!release`.  I'm tempted to push the GH Merge button just to see what happens...  :)

**Pull request merged**
